### ISSUE TITLE
[BUG] Bot is offline again

### ISSUE THREAD

**Issue by Pr3ng8** [andretkachenko/nexus-bot#100]
Hello, I just wanted to report that the bot has been going offline at often times recently. :/ May you check what cause it? Thank you so much!

**Comment by andretkachenko** [comment]
Hello @Pr3ng8 
Sorry for the delay. Some server issues occurred on the hosting.
Thank you for the feedback. I've restarted the bot and now it should be working fine.
Have a good day!
