### ISSUE TITLE
Add the possibility to use Stage Channels

### ISSUE THREAD

**Issue by BenNotix** [andretkachenko/nexus-bot#118]
Hello ! 
I think it would be useful to make the bot compatible with Stage Channels. 

Thanks in advance!

**Comment by andretkachenko** [comment]
Hello @BenNotix 
Could you please clarify?
Stage Channels is the new feature, and I haven't been exploring it yet. It's not creating a linked text channel for it?

**Comment by BenNotix** [comment]
No. The bot is not compatible with this new feature, it's a shame... 
That's why you'll have to adjust the bot so that it creates a text room linked to the stage channels.

**Comment by andretkachenko** [comment]
All right. Let me try it out on my test server.
I will keep you posted on updates here in the comments.

**Comment by BenNotix** [comment]
All right! Thanks 😀

**Comment by andretkachenko** [comment]
@BenNotix 
Currently, I'm unable to make complete stage channel support - the linked text channel will be created with the `undefined-text` name, as the bot can't find stage channels - it's the different type of channels, and for now, it's hardly maintainable.
But fortunately, that's the only problem with the staged channels regarding my bot - you will need to rename the text channel after it's created, other than that it should work as the others.
The workaround has just been deployed, so should be already available to you.
Feel free to comment/reopen this ticket in case you see any issues with that.

**Comment by BenNotix** [comment]
All right! It works perfectly. Thanks for being so quick :)
