### ISSUE TITLE
Add the possibility to link an existing text room with a voice room

### ISSUE THREAD

**Issue by BenNotix** [andretkachenko/nexus-bot#119]
I think it would be helpful if we could link an audio room with an existing text room. 

This would also allow us to link multiple text channels with a single voice channel.

**Example:**
`sudo voicelink [Voice Channel ID] [Text Channel ID]`

**Comment by andretkachenko** [comment]
I've been thinking about creating a feature like that for a while, but I saw it as a way to fix corrupted voice/text channel relations.
Regarding the multiple-to-one relation, both n-voices/1-text and 1-voice/n-texts - that kind of feature was already requested once, but it looks like an overburdening. I can't imagine a practical application for that to justify additional processing for the feature.

**Comment by BenNotix** [comment]
I understand...
The functionality that would allow to link an already existing salon would be a good thing, for example if we already have a salon created that we want to keep.

**Comment by andretkachenko** [comment]
The feature has just been deployed.
Feel free to reopen/comment on this ticket in case you face any issues with it.
