### ISSUE TITLE
Add an automatic deletion option for text rooms linked to voice rooms that are deleted

### ISSUE THREAD

**Issue by BenNotix** [andretkachenko/nexus-bot#120]
It would be useful to add an option that can be turned on and off, so that when a voice room is deleted, the text room that is linked to it is also deleted automatically. 
This is useful when we create temporary rooms and forget to delete the text room linked to it.

**Example of the setup command:** 
`sudo autotextdelete <True or False>`

**Comment by andretkachenko** [comment]
Agree, this one is a good quality-of-life feature.
However, are you sure that it should be something to be toggled via the command? My view on that for now that it should be working all the time, as soon as the voice channel is deleted, the linked voice channel should be deleted as well.

**Comment by BenNotix** [comment]
I agree with you!

**Comment by andretkachenko** [comment]
The feature has just been deployed.
Feel free to reopen/comment in this ticket in case you face any issues with it.

**Comment by andretkachenko** [comment]
The feature has just been deployed.
Feel free to reopen/comment in this ticket in case you face any issues with it.
