### ISSUE TITLE
[BUG] Impossible to make the ignore command on a stage channel

### ISSUE THREAD

**Issue by BenNotix** [andretkachenko/nexus-bot#132]
It is impossible to execute the command `sudo ignore 1 <a stage channel id` on a stage channel.

**Comment by BenNotix** [comment]
https://i.discord.fr/UVj.png

**Comment by andretkachenko** [comment]
Hello @BenNotix 
I can reproduce it, yet it will hang like that for some time - I'm waiting for the DIscordJS update to version 13, where stage channels should already be supported.
Once v13 is released, I will work on the fix.

**Comment by BenNotix** [comment]
Okay, thanks.

**Comment by BenNotix** [comment]
Okay, indeed, that's a good idea! Thanks :)

**Comment by andretkachenko** [comment]
Hi @BenNotix 
v13 upgrade is currently being deployed.
Fix for this should be available for you in few minutes.
Beware that commands were overhauled, so there's no interaction with the bot via messages anymore - within 1 hour there should be slash commands available for the bot on every server.
Have a great day!
