### ISSUE TITLE
Sudo ignore assist

### ISSUE THREAD

**Issue by Dhmee** [andretkachenko/nexus-bot#140]
Hi again , thanks for the fast respond and action , after the update ignore function not responding maybe i'm doing something wrong ? ( channel - category both ) https://prnt.sc/12t7c5y

**Comment by Dhmee** [comment]
https://prnt.sc/12t88ik

**Comment by andretkachenko** [comment]
It's ok if it says nothing - `sudo map` is verbose in chat because it's a dangerous command, which can break other channels.
Most of the commands either respond only when something wrong, or don't respond at all.
You can just check it by joining the channel you just ignored.

**Comment by andretkachenko** [comment]
@Dhmee I can also confirm that `841720952218845184` channel was indeed marked to be ignored
