### ISSUE TITLE
Not adding users to text channel

### ISSUE THREAD

**Issue by shukumei7** [andretkachenko/nexus-bot#142]
The bot was working before and thus I have text channels set up.
Now the bot doesn't work at all. Not creating new channels nor adding users to existing ones.

**Comment by andretkachenko** [comment]
Hello @shukumei7 
Could you please clarify the problems you are facing?
I've just checked the bot myself, and it properly creates new text channels and updates view permissions upon joining/leaving the voice channel.
I'm seeing a lot of the logs that show that the bot lacking permissions to change view permissions for someone, maybe it's your case. Could you please also check permissions set up for the Nexus in the role and channel/category?

**Comment by shukumei7** [comment]
It seems to stop working if I move the channels around.

Deleting the channels fixes this problem and allows the bot to create new
channels that work perfectly until moved (a lot) again.

**Comment by andretkachenko** [comment]
The bot does not change any settings for channels when they are moved to another place/another category.
What can possibly happen is:
- Channel synchronizes its permissions with the category, which does not let the Nexus bot work as expected
- Channel is moved to the category which was set to be in Ignore List (`sudo ignore 1 <categoryId>`), so it's no longer handled by the bot.

**Comment by shukumei7** [comment]
I guess I understand that. I think I was under the impression that the
channel overrides the permissions of the categories granting the bot access
to a channel regardless of category.

Sorry for the confusion.

**Comment by andretkachenko** [comment]
@shukumei7 depends on whether the sync option was enabled for the channel or not.
If you move a channel that has permission synchronization with the category set to be disabled, it will stay with its permission even after you move it. But if it is enabled, a new category will enforce its ruleset on the channel.
