### ISSUE TITLE
[BUG] Bot is not changing permissions properly 

### ISSUE THREAD

**Issue by RiveraRBB** [andretkachenko/nexus-bot#149]
**Describe the bug**
When you join a VC, a text channel is created and bot changes permissions to make the channel visible to you, but when you leave bot doesn't change any permissions

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup the bot
2. Join a VC and check permissions of the text channel
3. Leaves the VC and check again permissions of the same text channel
4. And make sure the bot is admin so he can do anything

**Expected behaviour**
Bot should change permissions again to make not visible

**Screenshots**
Just test yourself :)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Actual one (I don't know how to check it on PC)

**Additional context**

**Comment by andretkachenko** [comment]
Hello @RiveraRBB 
I've just tried to reproduce it, everything worked as expected for me (tested with the 2nd account, which is not an admin on a server).
Is there a chance that a user that was moving between channels is an admin?

**Comment by RiveraRBB** [comment]
Yes, it is an admin, was that the problem?

**Comment by RiveraRBB** [comment]
I'm testing the bot in a private server to use it then in a 6k members.

I'm just interested in the feature of sudo map, if you can confirm me that it will work like I need I will be so grateful with you:

I use the command **sudo map 1 VOICECHANNELID TEXTCHANNELID**, so everytime an user joins that VC the Text Channel will be visible for them (and I will set to ignore every other channels because I just need in 2-3 of them)

Will this be working right?

**Comment by andretkachenko** [comment]
Bots can't hide channels from admins of the server, it's just not allowed by Discord.
Regarding map - it's an option to match text channel and voice channel.
For example, you have `text-1` and `Voice 1` channels, which are just two regular channels. If you want `text-1` to work as a linked text channel for `Voice 1`, you can use `sudo map` command.
[Here's the link to the wiki with the info about command and how to get channel ids](https://github.com/andretkachenko/nexus-bot/wiki/sudo-map)

**Comment by andretkachenko** [comment]
I've managed to replicate the issue when I added my bot to a different server. Investigating it.
However, the bot works as expected with admin rights. May be some changes in the permission from the Discord, don't know yet.

**Comment by andretkachenko** [comment]
@RiveraRBB I assume, there's no bug then? If you want to test how regular users will see linked text channels, you probably either need to summon a friend for help or just create 2nd test account and test it with it as a regular user.

**Comment by RiveraRBB** [comment]
I just did it with a second account but can't get sudo map to work, is it working properly with you (just the sudo map feature)

**Comment by RiveraRBB** [comment]
I have made an override for both voice and text channel, so the bot has all the permissions, but when I join to the VC with my 2nd account (no admin), I can't see the text channel maped

**Comment by andretkachenko** [comment]
Yes, it is.
Make sure you copied [right IDs](https://github.com/andretkachenko/nexus-bot/wiki/How-can-I-find-User-ID-Channel-ID-Guild-ID%3F).
Then use like `sudo map 1 725696155480096839 827258575747416066`, where 1st set of digits is the ID of my voice channel, and 2nd set - ID of the text channel

**Comment by andretkachenko** [comment]
If you are not sure that channels were mapped, you can use `sudo map 0 725696155480096839 827258575747416066` (stress on **0** after the` map`). In case your voice channel has linked text channel, the bot will respond with `Voice Channel already has mapped Text Channel`

**Comment by RiveraRBB** [comment]
I finally got it working, I don't know why but bot needs Manage Channel permissions to work, not only have it in both Voice and Text Channels, thanks a lot!

**Comment by andretkachenko** [comment]
Well, that's not surprising.
Bot requires Manage Channels permission when you first invite it, plus it's mentioned here [for troubleshooting purposes](https://github.com/andretkachenko/nexus-bot/wiki/The-bot-does-not-behave-as-expected#first-ensure-that-the-bot-has-all-permissions-needed-for-proper-work).
Glad you managed to set up it to your taste.
