### ISSUE TITLE
[BUG] Impossible to make the map command on a stage channel 

### ISSUE THREAD

**Issue by BenNotix** [andretkachenko/nexus-bot#151]
**Describe the bug**
An error occurs when we try to run the `sudo map` command on a stage channel.

**To Reproduce**
Steps to reproduce the behaviour:
1. Execute the command `sudo map [0/1] {stageChannelId} {textChannelId}`.
2. Bot response: _Error processing command - specified channel ID does not belong to a voice channel_

**Expected behaviour**
I wanted to link the stage channel with a text channel, as it is already possible to do automatically without the command.

**Screenshots**
![Screen 1](https://unosial.uno/6jp8ncl.png)

**Comment by andretkachenko** [comment]
Hi @BenNotix 
v13 upgrade is currently being deployed.
Fix for this should be available for you in few minutes.
Beware that commands were overhauled, so there's no interaction with the bot via messages anymore - within 1 hour there should be slash commands available for the bot on every server.
Have a great day!
