### ISSUE TITLE
Add ability to add roles to perm view channel permissions 

### ISSUE THREAD

**Issue by Corbin602** [andretkachenko/nexus-bot#154]
Something like:
sudo add [0/1] @{user/role}

This way my mods can always have access without joining the VC

Thanks for the great bot!

**Comment by andretkachenko** [comment]
Hi @Corbin602 
You already can do that by using `/skip` slash commands.
Using it you will make preferred user/role ignored while making adjustments to visibility settings. All you have to do after that - make sure to provide `Read Channel` permission for the desired user/role.
