### ISSUE TITLE
Ignore command doesnt work [BUG] 

### ISSUE THREAD

**Issue by Masono03** [andretkachenko/nexus-bot#156]
**Describe the bug**
using the ignore command does nothing. i tried on multiple channels and tried all options but it still makes new text channels for every vc joined even if i used the ignore command on it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use ignore command to ignore a channel
2. join the channel u tried to ignore
3. you still get a text channel to it

**Expected behaviour**
Not getting a text channel made for that vc.

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX (dunno why thats needed tbh?)
 - Version i just invited the public bot so i dont know?

**Additional context**
i just now invited the bot to my discord and yah other features seem to work but ignore is useless

**Comment by andretkachenko** [comment]
Hi @Masono03 
You're probably using old text commands, which were deprecated.
Try to use the slash command by starting typing /ignore. Just make sure you use the Nexus bot command (there might be several commands with the same name from different bots).

**Comment by Masono03** [comment]
i did use the slash and made sure it was the right bot it also gave me the "done" answer but nothing happens.

**Comment by andretkachenko** [comment]
Well, I've checked it before I answered you and also rechecked it now. Work good enough for me.
I've created a new voice channel, used `/ignore True wer`, then join `wer` channel. No `wer-text` is created for me.

**Comment by Masono03** [comment]
does it only work with new channels? i have a lot of already established text channels and would rather not need to remake them :/ and for me it just doesnt wanna work i guess ima have to find a diffrent bot then but thx for answering tho.

**Comment by andretkachenko** [comment]
@Masono03  what do you expect from this command? If you want messages persist in linked text channel, you're using wrong command, see [/preserve](https://github.com/andretkachenko/nexus-bot/wiki/preserve)

**Comment by Masono03** [comment]
also maybe important to note: i kicked the bot from the server and reinvited it to see if that would fix it but now the / commands for it wont even show up anymore at all

**Comment by Masono03** [comment]
i was thinking if i use that and target a vc it would not automatically make text channels for that vc but it still does

**Comment by andretkachenko** [comment]
As far as I remember, Discord does not add slash commands immediately, that's specific of the slash command function itself.
Ignore command allows disabling linked text channel creation for the specific voice channels.
In my example, I have `wer` (doesn't matter whether it's fresh VC or old one, only that it doesn't have a related `wer-text` channel yet), and by using `/ignore True wer` I make sure that `wer-text` won't be created when I join it.

**Comment by Masono03** [comment]
yes thats the functionality i was expecting but it kept creating text channels anyway

**Comment by andretkachenko** [comment]
can you add me at Discord (Undrimnir#3940), add me to your server and give me rights to test things out? I'm curious what's going on

**Comment by andretkachenko** [comment]
Issue resolved in Discord, I am closing the ticket here.
