### ISSUE TITLE
No command is working

### ISSUE THREAD

**Issue by GrzegorzWalewski** [andretkachenko/nexus-bot#157]
**Describe the bug**
No command is working. When I type `/` in my command channel all other bots automatically hint me with their commands, nexus doesn't

**To Reproduce**
Steps to reproduce the behaviour:
1. Type any command
2. It's not working

**Screenshots**
![obraz](https://user-images.githubusercontent.com/25950627/156614169-01a3382b-0833-4336-9c4d-70a3319a07b8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Discord client
 - Version: newest

**Comment by andretkachenko** [comment]
Hello.
I'm sorry it doesn't work as expected.
Unfortunately, I can't investigate this at the moment - I'm in Ukraine.
Maybe I will be able to take a look at it again after war.
Hope you doing well. Take care

**Comment by andretkachenko** [comment]
Hi @GrzegorzWalewski 
Want to ask do you still face this issue? 
I know that sometimes slash commands take time to appear on a server once the bot was invited, but it should appear within hour.
If it didn't - could you please try to kick the bot and invite it again via the link provided in [readme](https://github.com/andretkachenko/nexus-bot#want-to-use-at-your-server).

**Comment by andretkachenko** [comment]
Closing this ticket for now.
If you ever want to resume the conversation - feel free to reopen the ticket.
