### ISSUE TITLE
the bot is down on my server but here the status shows as offline

### ISSUE THREAD

**Issue by hariztek** [andretkachenko/nexus-bot#158]
the bot on my server is down for some reason but it shows online here

**Comment by andretkachenko** [comment]
Hello.
I'm sorry it doesn't work as expected.
Unfortunately, I can't investigate this at the moment - I'm in Ukraine.
Maybe I will be able to take a look at it again after war.
Hope you doing well. Take care

**Comment by Ghalban** [comment]
> Hello. I'm sorry it doesn't work as expected. Unfortunately, I can't investigate this at the moment - I'm in Ukraine. Maybe I will be able to take a look at it again after war. Hope you doing well. Take care

Take care Andre!! Stay safe!!

**Comment by andretkachenko** [comment]
@hariztek @Ghalban Hi everyone.
Sorry it took so long to figure this out.
I believe the issue should be resolved for now.
If you see that the bot is offline in Discord in the nearest days - feel free to ping me here or in #160  issue (I believe it's the same issue)

**Comment by feather410** [comment]
@andretkachenko I figured this is the best place to post. I've noticed the bot is down and has been for a while. Is it still being hosted?

**Comment by andretkachenko** [comment]
hi @feather410. it is still being hosted, but the hosting service started going dark for me for some reason. Let me check the bot and I'll get back to you

**Comment by andretkachenko** [comment]
@feather410 thank you for the ping. I've restarted the bot and I'll investigate the reason and how to prevent this.

**Comment by andretkachenko** [comment]
@feather410 I've decided to change hosting for the bot. Please keep me posted whether in this issue or create a new one (which one you prefer) if it becomes unresponsive again

**Comment by feather410** [comment]
Will do, thanks
