### ISSUE TITLE
[IDEA] Remove the permission for the user that left the channel instead of toggling them to deny

### ISSUE THREAD

**Issue by NeuTraLZero** [andretkachenko/nexus-bot#159]
**Is your feature request related to a problem? Please describe.**
It's very annoying to manage the permissions after so many have joined a channel and there's so many of them left there

**Describe the solution you'd like**
Just make the bot delete the permission for that user for the channel when they leave instead so it's way easier to manage

**Comment by andretkachenko** [comment]
Hello @NeuTraLZero 
I understand your confusion, and your idea should make QoL improvement without compromising functionality.
Unfortunately, your issue will have to hang here for the foreseeable future - I'm from Ukraine.
Hope I can return to this idea when the war is over.
Hope your doing great.

**Comment by andretkachenko** [comment]
Hi @NeuTraLZero 
Your proposed changes are now being deployed.
Thank you for your idea, you can check how it works now.
Feel free to comment here about your thoughts.
