### ISSUE TITLE
[IDEA] Member Join Message

### ISSUE THREAD

**Issue by feather410** [andretkachenko/nexus-bot#166]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I think it would be really interesting to include the ability to have a message sent when a user joins the voice channel inside of the text channel, and additionally when they leave. 
The message could be predefined and have the option to opt out/in or could have some customizability. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andretkachenko** [comment]
Hi @feather410 
Thank you for your suggestion.
To be honest, right now I'm not completely sold on this idea - if we start sending messages every time someone joins the voice channel, only those who are already there will see it. This means we are sending text notifications to the people, who already received sound notifications about that.
Another concern is that it might turn the channel into spam - in case someone joins/leaves the channel often and/or discussion in the linked text channel isn't active enough.
If you have another opinion, feel free to explain it here, and we can discuss it more.

**Comment by feather410** [comment]
I'm mostly suggesting because it was something my server really liked about the bot we used for this previously. We used Dyno, but that's the only part we used of it and it's behind a paywall so I wanted to end my subscription and found Nexus bot as an alternative. 
It would ping the new person who joins which both allows 1. the people in the chat to easily see who it was that joined which is especially helpful when there's a large amount of people in the voice call or you'd need to scroll to see the list of people in the voice. 
2. It alerts new people who have never been in the voice chat before that there's a special channel for it since it pings them to show the presence. 

The spam can be an issue at moments, but we've never found it to be too disruptive. Over time as you use the channel a lot you tend to get used to the random join and leave messages and just talk around it.

**Comment by andretkachenko** [comment]
@feather410 I decided to add this command.
It's currently being deployed, and should be available to all servers within 1 hour (probably even faster).
[here's the link with info about new command](https://github.com/andretkachenko/nexus-bot/wiki/announce)
It will be always disabled by default, so make sure to enable it using the command on your server.
Thank you again for your interest in the app.
Best regards
