### ISSUE TITLE
Text to Speech [IDEA]

### ISSUE THREAD

**Issue by dsk80004** [andretkachenko/nexus-bot#51]
I've been looking for a solution which allows our game server to integrate with a discord voice channel.

Ideally this would be a voice channel which can receive the in game text as an audio file. We already have discord text integration back and forth with the game working with out issue. I've considered just making the game server post to discord with 2 separate messages one with the prefix /tts, which would get removed automatically by discord. and the second post would just be the text. Though spamming a text channel with audio would be quite annoying. So a voice chat channel would be best.

I'm not even positive it bots are allowed to "speak" in audio channels, If this is possible I would greatly appreciate it. If not suggestions for alternatives would be appreciated.

**Comment by andretkachenko** [comment]
Hello.
Quite an uncommon approach to the discord bots.
This idea is interesting, but it is not related to the main purpose of the bot, and I have no intentions to make it more general-purpose swiss-knife-ish bot.
Regarding bots speaking in the voice channels - yes, you can do it. Actually, all music bots are made this way - they "speak" with music in your voice channel.
The catch with your case is to find proper TTS firmware. The one that comes in mind is Google TTS, but message length is limited to 200 characters in a free version (you can see pricing for the unlimited version).
As far as I understand your idea, you need a bot that will also have an open socket to listen for post request with the text, which will then be fed to the bot. That's how it looks for me right now.
I've made a bit of research on node js libraries for TTS, and it seems there's a huge library specifically made for Google TTS. So it would be like a music bot, but you will feed his queue not with the songs, but with the audio files returned by Google Cloud.
