### ISSUE TITLE
[BUG] When new user joins he sees all "invisible" channel

### ISSUE THREAD

**Issue by tilli123** [andretkachenko/nexus-bot#59]
Hey 
I created a Server with your bot it works perfectly!
But when I invite a new user (registered or without an account)

in the Browser and Android Version of Discord the new user sees all the Text Channels

After going through the voice channels the normal behaviour returns as intended by your bot

The channels are not in the nexus Categorie anymore

Any Ideas

Thanks for your Help :)

**Comment by andretkachenko** [comment]
Hello @tilli123.
Glad you liked it =)
I got the issue, will check it out later myself.
If you need a quick workaround before I try to reproduce it: check permissions that are set for the text channels - make sure that 'Read Messages' permission for '@everyone' is denied (X mark).
It's ok to move text channels to the other categories - bot functionality does not require them to be in a specific category, it just creates it in one spot as a default, most-likely-needed scenario. Feel free to move/rename them however you like.
But, there's a catch - if you move text channel to a different category, channel's permissions can sync with the category's permissions, which will remove the required state of 'Read Messages' permission for '@everyone'. No problem here, just double-check it and you should be fine.

Again, I will check it myself just to be clear and I will come back to you.
If this workaround works for you, please respond in this discussion so I know how everything is going.

Best regards

**Comment by tilli123** [comment]
> Hello @tilli123.
> Glad you liked it =)
> I got the issue, will check it out later myself.
> If you need a quick workaround before I try to reproduce it: check permissions that are set for the text channels - make sure that 'Read Messages' permission for '@everyone' is denied (X mark).

When I do that the normal user can't see it anymore when joining the voice channel. But maybe I am doing something wrong

> It's ok to move text channels to the other categories - bot functionality does not require them to be in a specific category, it just creates it in one spot as a default, most-likely-needed scenario. Feel free to move/rename them however you like.

Good to know, I just moved them to another category

> But, there's a catch - if you move text channel to a different category, channel's permissions can sync with the category's permissions, which will remove the required state of 'Read Messages' permission for '@everyone'. No problem here, just double-check it and you should be fine.
> 
> Again, I will check it myself just to be clear and I will come back to you.
> If this workaround works for you, please respond in this discussion so I know how everything is going.

No need rush thank you very much for your help
