### ISSUE TITLE
[IDEA] Would be awesome if You could choose what channels it works with,

### ISSUE THREAD

**Issue by Shadoweee77** [andretkachenko/nexus-bot#73]
Hey,
would it be possible so You could choose the channels You want the bot to monitor? I want to have like 3 specific chats that work like this - not all.

**Describe the solution you'd like**
Some sort off menu to let You choose via embed?

**Comment by andretkachenko** [comment]
Hello @Shadoweee77 
Thank you for your idea.
It's an interesting feature, I will try it out later on.
Right now I'm crunch IRL, so it may take a while before I will be able to work on it.
I will keep you posted here in the comments.

**Comment by arthprin** [comment]
Hi !
Any news about this feature?
It would be really useful and awesome

**Comment by andretkachenko** [comment]
Hi @Shadoweee77 @arthprin!
I've added a new feature to add/delete specific voice channels to the ignore list.
I've seen your proposition about making an embed to be able to choose which one to ignore. However, this solution will provide a significant load on the bot itself, which is going to cause a slow response from the bot in the long run.
Please check either readme of help command for the help.
NB: If you don't know how to find channel id - go to User Settings -> Appearance -> Advanced -> Developer Mode. This will add `Copy ID` button when you right-click any channel/server.

**Comment by andretkachenko** [comment]
If you see any issues/bugs/possible adjustments - feel free to comment here.
Have a good day!

**Comment by Shadoweee77** [comment]
Awesome, thanks! <3

**Comment by arthprin** [comment]
Hi @andretkachenko,

Thanks !

But I have a problem, every time I have:
`sudo ignore add 783964477271441419`
`Error processing command - specified channelId does not belong to a voice channel.`

However, I add the id of the voice channel, and I am the administrator of the server ...

**Comment by andretkachenko** [comment]
Hi @arthprin 
Please check it again, I've now deployed the fix for it.

**Comment by arthprin** [comment]
Hi @andretkachenko,

It's ok, thanks !

There are also small problems (nothing serious) in the readme and when we do the command "sudo help", I send you the screenshot: the command sudo ignore delete is not displayed correctly

![image](https://user-images.githubusercontent.com/39902254/100994917-67830a00-3557-11eb-8a53-52eb1fb67eed.png)

And the readme :

`sudo ignore add {channelId} - skip voice channel with the specified id when checking for linked text channel. Example: ${this.config.prefix}ignore add 717824008636334130. Requires user to have admin rights.

sudo ignore delete {channelId} - remove voice channel with the specified id from ignore list. Example: ${this.config.prefix}ignore delete 717824008636334130. Requires user to have admin rights.`

**Comment by andretkachenko** [comment]
Ah, my bad. Don't know how I missed that. 
I will fix this as well, thank you.

**Comment by andretkachenko** [comment]
@arthprin done and done.
Thank you for your time! I appreciate your feedback.

**Comment by arthprin** [comment]
No problem @andretkachenko! Thank you for your contribution with this really useful bot, which was terribly missing on Discord :)

**Comment by Shadoweee77** [comment]
Not sure if this is a bug or not yet implemented, but I do not get any feedback from the bot upon adding a channel to ignored list. Also printing a list would be cool. Either way, thanks a million!
![image](https://user-images.githubusercontent.com/20088126/101075451-53b0c580-35a2-11eb-9ad9-e37c989c3516.png)

**Comment by andretkachenko** [comment]
It's just not implemented. If bot didn't respond with an error - then everything works just fine.
Regarding the list of ignored channels - if the bot returns just list of channel IDs, then it will not be user-friendly and that much useful.
And if I implement it to fetch channel names for being better for a user to look through - I expect it to have a serious impact on bot's responsiveness and performance, taking into account that it is used on 150+ servers already and the number keeps growing.
However, thank you for the idea, I will consider making it if I find any suitable solution for it.

**Comment by andretkachenko** [comment]
@Shadoweee77 btw, I can say you that I've just checked the database and these channels you've been trying to add to ignore list were successfully added there, in case you are worried about that.
