### ISSUE TITLE
[BUG] Nexus is down

### ISSUE THREAD

**Issue by arthprin** [andretkachenko/nexus-bot#85]
Hi ! :)

The bot has been disconnected since this morning, I don't know if you are aware of it, but it was to warn you :)

Thanks

**Comment by arthprin** [comment]
Just as I am writing the message it is back online ... Sorry for the useless issue

**Comment by andretkachenko** [comment]
Hi @arthprin 
Thank you for the info.
How long was it offline?

**Comment by arthprin** [comment]
He was offline since 11am (UTC + 2) but is back online

**Comment by andretkachenko** [comment]
Okay, thank you for the info.
In case it is offline later on - don't hesitate to reopen this issue.
I'm getting mail from the Github when someone creates/reopens/comments on the issue, so I will be able to manually restart bot quickly (most of the time)

**Comment by andretkachenko** [comment]
I will also investigate this one, to make sure it is not a code-related issue I can fix.
But for now, I think it's something going on on the hosting side.
Sorry for the inconvenience.

**Comment by arthprin** [comment]
Okay, no worries, thank you for your responsiveness :)
