### ISSUE TITLE
Would be very nice to have the option to not delete the messages created in the channel. [IDEA] 

### ISSUE THREAD

**Issue by pokropski** [andretkachenko/nexus-bot#89]
**Is your feature request related to a problem? Please describe.**

I would like the option to exclude a text channel from the auto wipe function of deleting all of the messages after people leave the corresponding voice channel. This would allow the text channels to be a more permanent fixture for the moderator to use for reference. This also prevents accidentally losing items when leaving prematurely or inadvertently. 

**Describe the solution you'd like**
I would like the option for a created text channel that the moderator of the server to be excluded from the "delete all messages except pinned items" step. Something along the lines of "sudo preserve add {channel id}" and a "sudo preserve delete {channel id}" to define if a text channel should have it contents wiped. This would require the text channel to already exist and be visible to enter by the moderator (currently already a limitation/feature of the bot). 

**Describe alternatives you've considered**
The only alternative at the moment is to pin all messages ahead of time with no recourse once you have left the voice server. This is quite tedious and does not account for disconnects. 

**Additional context**
N/A

**Comment by andretkachenko** [comment]
Hello @pokropski 
Woah, thank you for such a detailed description.
These linked text channels were expected to be more like a temporary way to transfer links, files or commute with each other, that's why auto clearing feature was developed from the start.
I understand your idea, let me assess it and I will get back to you when  I will have any updates in this regard.

**Comment by andretkachenko** [comment]
Hi @pokropski.
The feature you requested was just deployed
Please refer to the command list either in [the readme](https://github.com/andretkachenko/nexus-bot#existing-commands) or in Discord via `sudo help` command.
Feel free to reopen and/or comment in this ticket in case you face any issue.
Have a good day!

**Comment by pokropski** [comment]
Firstly, thank you so much for working on this right away. I didn't expect that at all, and I really appreciate it. Thank you again! 

This is working perfectly, and you've made an awesome bot!

**Comment by andretkachenko** [comment]
Thank you. I'm glad you like it :)
I've been working on similar moderation configuration for my lfg bot not so long ago, so I had some groundwork to rely upon already.
Plus it was a valid and well-described idea, so overall it didn't take too much time to implement it.
