### ISSUE TITLE
[IDEA] Include User/Role Ignoring

### ISSUE THREAD

**Issue by ScarVite** [andretkachenko/nexus-bot#92]
**Is your feature request related to a problem? Please describe.**
I gave my Mod Roles permissions to read the text channels, and whenever they join and then leave the channel, they get their permissions taken away, because of your user override.

**Describe the solution you'd like**
Add a command to blacklist users/roles so that their permission become "stuck" and don't get overwritten every time you join and leave a vc

**Describe alternatives you've considered**
Manually deleting their override

**Comment by andretkachenko** [comment]
@ScarVite feature you requested has just been retested and deployed.
Refer to the README here or `sudo help` command of the bot.
NB: `sudo ignore` and `sudo preserve` commands received updates as well, so if you use them, check them in help as well.
