### ISSUE TITLE
[BUG] Bot is offline

### ISSUE THREAD

**Issue by sodadealer** [andretkachenko/nexus-bot#99]
Hello, I just wanted to report that the bot has been going offline at often times recently. At the moment I'm writing this it still hasn't come back online and it has already been more than 12 hours since it went offline, this also happened the day before not sure for how long but it was a few hours I'm pretty sure.

**Comment by andretkachenko** [comment]
Hello @sodadealer 
Sorry for the delay. Some server issues occurred on the hosting.
Thank you for the feedback. I've restarted the bot and now it should be working fine.
Have a good day!

**Comment by andretkachenko** [comment]
Actually, I didn't know about these kinds of issues. Maybe occurred when I was offline.
Feel free to reopen this ticket or create a new one if this happens, I may find out about the bot shut down earlier then and fix it faster.
